site_name: Uni{form|corn} tool kit
markdown_extensions:
  - codehilite
  - attr_list
  - admonition
  - markdown.extensions.footnotes
  - markdown.extensions.smarty
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.emoji


extra:
  search:
    tokenizer: '[\s\-\.::]+'

theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'deep orange'
  font:
    text: 'PT Serif'
    code: 'Inconsolata'
  logo: 'data/logo_utk.png'

extra_css:
  - extras.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

repo_name: 'utk-team/utk'
repo_url: 'https://github.com/utk-team/utk'
edit_uri: ''


docs_dir: 'sources-doc'
site_dir: 'docs'

nav:
  - Home: 'index.md'
  - Samplers:
    - All samplers: 'samplers.md'
    - Faure: 'sampler_faure.md'
    - Halton: 'sampler_halton.md'
    - Hammersley: 'sampler_hammersley.md'
    - Niederreiter: 'sampler_niederreiter.md'
    - Sobol (Joe&Kuo): 'sampler_sobolkuo.md'
    - Sobol (Original): 'sampler_sobolindiced.md'
    - Owen Scrambled Sobol: 'sampler_owen.md'
    - Rank 1: 'sampler_rank1.md'
    - LDBN: 'sampler_ldbn.md'
    - BNLD Sequences: 'sampler_BNLDS.md'
    - AA Patterns: 'sampler_aapatterns.md'
    - ART: 'sampler_art.md'
    - CVT : 'sampler_CVT.md'
    - CapCVT: 'sampler_CapCVT.md'
    - Forced Random: 'sampler_forced_random.md'
    - FPO: 'sampler_FPO.md'
    - Penrose: 'sampler_penrose.md'
    - BNOT: 'sampler_BNOT.md'
    - Dart Throwing: 'sampler_dart_throwing.md'
    - Fast Poisson: 'sampler_fastpoisson.md'
    - CMJ: 'sampler_cmj.md'
    - Hexagonal grid: 'sampler_hexagonal_grid.md'
    - Korobov: 'sampler_korobov.md'
    - NRooks: 'sampler_nrooks.md'
    - Regular grid: 'sampler_regular_grid.md'
    - Single Peak: 'sampler_singlepeak.md'
    - Step: 'sampler_step.md'
    - Stratified: 'sampler_stratified.md'
    - Whitenoise: 'sampler_whitenoise.md'
  - Discrepancy Evaluation:
    - Star discrepancy: 'discrepancy_star_disc.md'
    - L2 Discrepancy: 'discrepancy_l2_disc.md'
    - Centered L2 Discrepancy: 'discrepancy_centered_l2_disc.md'
    - Unanchored L2 Discrepancy: 'discrepancy_unanchored_l2_disc.md'
    - Symmetric L2 Discrepancy: 'discrepancy_symmetric_l2_disc.md'
    - Generalized L2 Discrepancy: 'discrepancy_generalized_l2_disc.md'
    - Fast bounds on the Star Discrepancy: 'discrepancy_bounds_star_disc.md'
  - Classes:
    - Doxygen: 'doxygen.md'
    - I/O formats: 'io_format.md'
  # - Scrambing:
  #   - Cranley Patterson:
  #   - Digital XOR:
  #   - Owen Scrambling:
  # - Integration:
  #   - NSpheres:
  #   - Centered Gaussian:
  #   - Cornered Gaussian:
  #   - Gaussian:
  #   - Image:
  #   - Box arrangement:
  #   - Triangle arrangement:
